# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[4,)"
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="tgbridge"
version="${version}"
displayName="Telegram Bridge"
authors="vanutp"
description="Sync your game with Telegram"
logoFile="icon.png"
displayURL="https://github.com/vanutp/tgbridge"
displayTest="IGNORE_ALL_VERSION"
[[dependencies.tgbridge]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tgbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
